"""create militares table and update users

Revision ID: 1f9de453d4af
Revises: dfa056c24210
Create Date: 2026-09-05 11:49:23.177117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9de453d4af'
down_revision: Union[str, Sequence[str], None] = 'dfa056c24210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('militares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('saram', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('posto_graduacao', sa.String(), nullable=False),
    sa.Column('nome_guerra', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_militares_saram'), 'militares', ['saram'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('militar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['militar_id'], ['militares.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('militar_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_militares_saram'), table_name='militares')
    op.drop_table('militares')
    # ### end Alembic commands ###
